apiVersion: v1
kind: ConfigMap
metadata:
  name: kiali
  labels:
    app: kiali
    version: v0.9.0
data:
  config.yaml: |
    server:
      port: 20001
      web_root: /
    external_services:
      jaeger:
        url: jaeger-query
      grafana:
        url: grafana
