apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: alphabet-service
spec:
  hosts:
  - alphabet-service
  http:
  - fault:
      abort:
        httpStatus: 500
        percent: 100
    route:
      destination:
        host: alphabet-service
        subset: v1
